USE [pollor-db]

GO

/* DROP FOREIGN KEYS CONSTRAINTS */
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='FK_poll_user')
ALTER TABLE polls
DROP CONSTRAINT FK_poll_user;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='FK_answer_poll')
ALTER TABLE answers
DROP CONSTRAINT FK_answer_poll;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='FK_vote_answer')
ALTER TABLE votes
DROP CONSTRAINT FK_vote_answer;

/* DROP PRIMARY KEYS CONSTRAINTS */
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME ='PK_users')
ALTER TABLE users
DROP CONSTRAINT PK_users;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME ='PK_polls')
ALTER TABLE polls
DROP CONSTRAINT PK_polls;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME ='PK_answers')
ALTER TABLE answers
DROP CONSTRAINT PK_answers;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME ='PK_votes')
ALTER TABLE votes
DROP CONSTRAINT PK_votes;

/* DROP TABLES */
DROP TABLE dbo.users
DROP TABLE dbo.polls
DROP TABLE dbo.votes
DROP TABLE dbo.answers
